require:
  - standard
  - rubocop-rspec

inherit_gem:
  standard: config/base.yml

AllCops:
  NewCops: disable

RSpec/NestedGroups:
  Max: 5

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MessageSpies:
  EnforcedStyle: receive
